
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: List Services
        uses: lightbend/kalix-action@v3
        with:
          cmd: "services list"
        env:
          token: ${{ secrets.TOKEN }}
          project: ${{ secrets.PROJECT }}
