version: '2'
services:
  seed:
    container_name: nike-inventory-seed-1
    image: "nike-inventory:latest"
    ports:
      - '2551:2551'
      - '8080:8080'
    environment:
      RUN_LOCAL: 'true'
      CLUSTER_PORT: 2551
      CLUSTER_IP: seed
      SEED_PORT_2551_TCP_ADDR: seed
  node1:
    image: "nike-inventory:latest"
    ports:
      - '2552:2552'
    environment:
      RUN_LOCAL: 'true'
      CLUSTER_PORT: 2552
      CLUSTER_IP: node1
      SEED_PORT_2551_TCP_ADDR: seed
