version: "3"

services:
  scylla-db:
    image: scylladb/scylla:latest
    ports:
      - "9042:9042"

  tenant-service:
    image: improving-app-tenant:latest
    ports:
      - "8080:8080"
    depends_on: ["scylla-db"]
