version: "3"

services:
  scylla-db:
    image: scylladb/scylla:latest
    ports:
      - "9042:9042"

  gateway-service:
    image: improving-app-gateway:latest
    ports:
      - "8090:8090"
    depends_on: ["scylla-db"]

  member-service:
    image: improving-app-member:latest
    ports:
      - "8081:8081"
    depends_on: ["scylla-db"]
