apiVersion: apps/v1
kind: Deployment
metadata:
  name: improving-app
  labels:
    app: improving-app
spec:
  selector:
    matchLabels:
      app: improving-app
  template:
    metadata:
      labels:
        app: improving-app
    spec:
      containers:
      - name: tenant
        image: library/improving-app-tenant:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: Never
      - name: organization
        image: library/improving-app-organization:latest
        ports:
        - containerPort: 8082
        imagePullPolicy: Never
      - name: member
        image: library/improving-app-member:latest
        ports:
        - containerPort: 8081
        imagePullPolicy: Never
      - name: store
        image: library/improving-app-store:latest
        ports:
        - containerPort: 8083
        imagePullPolicy: Never
      - name: event
        image: library/improving-app-event:latest
        ports:
        - containerPort: 8084
        imagePullPolicy: Never
      - name: product
        image: library/improving-app-product:latest
        ports:
        - containerPort: 8085
        imagePullPolicy: Never
      - name: gateway
        image: library/improving-app-gateway:latest
        ports:
        - containerPort: 9000
        imagePullPolicy: Never
      nodeSelector:
        kubernetes.io/arch: arm64
      hostNetwork: true