apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: improving-app
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: improving-app
  labels:
    app: improving-app
spec:
  selector:
    matchLabels:
      app: improving-app
  template:
    metadata:
      labels:
        app: improving-app
    spec:
      containers:
      - name: tenant
        image: weinyopp/improving-app-tenant:latest
        ports:
        - containerPort: 8080
      - name: organization
        image: weinyopp/improving-app-organization:latest
        ports:
        - containerPort: 8082
      - name: member
        image: weinyopp/improving-app-member:latest
        ports:
        - containerPort: 8081
      - name: store
        image: weinyopp/improving-app-store:latest
        ports:
        - containerPort: 8083
      - name: gateway
        image: weinyopp/improving-app-gateway:latest
        ports:
        - containerPort: 9000
      nodeSelector:
        kubernetes.io/arch: arm64