apiVersion: v1
kind: Service
metadata:
  name: scylla-db
spec:
  selector:
    app: scylla-db
  clusterIP: None
  ports:
    - port: 9042
      targetPort: 9042
---
apiVersion: v1
kind: Pod
metadata:
  name: scylla-db
  labels:
    app: scylla-db
spec:
  hostname: scylla-db
  setHostnameAsFQDN: true
  containers:
    - image: scylladb/scylla:latest
      name: scylla-db
      ports:
        - name: scylla-db
          containerPort: 9042
  hostNetwork: true