apiVersion: v1
kind: Service
metadata:
  name: scylla
spec:
  selector:
    app: scylla
  clusterIP: None
  ports:
    - port: 9042
      targetPort: 9042
---
apiVersion: v1
kind: Pod
metadata:
  name: scylla
  labels:
    app: scylla
spec:
  hostname: scylla-db
  setHostnameAsFQDN: true
  containers:
    - image: scylladb/scylla:latest
      name: scylla
      ports:
        - name: scylla
          containerPort: 9042
  hostNetwork: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scylla
  labels:
    app: scylla
spec:
  selector:
    matchLabels:
      app: scylla
  template:
    metadata:
      labels:
        app: scylla
    spec:
      containers:
        - name: scylla
          image: scylladb/scylla:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9042
      hostNetwork: true