apiVersion: v1
kind: Service
metadata:
  name: scylla-db
spec:
  type: NodePort
  selector:
    app: scylla-db
  ports:
    - port: 9042
      targetPort: 9042
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scylla-db
  labels:
    app: scylla-db
spec:
  selector:
    matchLabels:
      app: scylla-db
  template:
    metadata:
      labels:
        app: scylla-db
    spec:
      containers:
        - name: scylla-db
          image: scylladb/scylla:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9042
      hostNetwork: true