apiVersion: v1
kind: Service
metadata:
  name: inventory-query-service
  namespace: inventory-query
spec:
  type: LoadBalancer
  selector:
    app: inventory-query
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080