apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-query
  namespace: inventory-query
spec:
  replicas: 
  template:
    spec:
      containers:
        - name : inventory-query
          imagePullPolicy: Always
          env:
            - name: PROJECTION_JDBC_URL
              valueFrom:
                configMapKeyRef:
                  name: jdbc-info
                  key: projection_jdbc_url