apiVersion: apps/v1
kind: Deployment
metadata:
  name: projection_jdbc
spec:
  replicas:
  template:
    spec:
      containers:
          env:
            - name: PROJECTION_JDBC_URL
              value: "jdbc:postgresql:///postgres?cloudSqlInstance=nike-pov:us-east4:nike1&socketFactory=com.google.cloud.sql.postgres.SocketFactory"
