apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: inventory-query
  name: inventory-query
  namespace: inventory-query
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-query
  template:
    metadata:
      labels:
        app: inventory-query
    spec:
      containers:
        - name: inventory-query
          image: {TODO:FULL PATH TO ARTIFACT}
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 20
          ports:
            - name: management
              containerPort: 8558
              protocol: TCP
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: REQUIRED_CONTACT_POINT_NR
              value: "2"
