apiVersion: v1
kind: ConfigMap
metadata:
  name: jdbc-info
data:
  projection_jdbc_url: "jdbc:postgresql:///postgres?cloudSqlInstance=reference-applications:us-east4:db-1&socketFactory=com.google.cloud.sql.postgres.SocketFactory"
