apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-domain
  namespace: inventory-domain
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name : inventory-domain
          imagePullPolicy: Never  #assumption is that the image has been loaded into minikube with minikube image load imagename:tag - alternately see here https://stackoverflow.com/questions/42564058/how-to-use-local-docker-images-with-minikube#:~:text=Set%20the%20environment%20variables%20with,try%20to%20download%20the%20image.
          env:
            - name: PERSISTENCE_JDBC_URL
              value: "jdbc:postgresql:///postgres?cloudSqlInstance=nike-pov:us-east4:nike1&socketFactory=com.google.cloud.sql.postgres.SocketFactory"
