apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../../bases/domain/
- ../shared/ # to include the projection-secret file
resources: 
- persistence-secret.yaml
namespace: inventory-domain
patches :
- path: domain-deployment-patches.yaml
  target: 
    kind: Deployment
    labelSelector: "app=inventory-domain"